---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# Backstage Portal itself
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal
  title: Backstage Developer Portal
  description: Internal developer portal for My Company
  annotations:
    github.com/project-slug: mvp-glaciar-org/devopsdaysba
  links:
    - url: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fecs$252Fbackstage-mvp-backstage
      title: Backend Logs (CloudWatch)
      icon: dashboard
    - url: https://console.aws.amazon.com/ecs/v2/clusters/backstage-mvp-cluster/services/backstage-mvp-service/health?region=us-east-1
      title: ECS Service
      icon: cloud
    - url: https://backstage.glaciar.org
      title: Production Portal
      icon: web
spec:
  type: service
  lifecycle: production
  owner: Pabloin
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    backstage.io/techdocs-ref: dir:./example-docs
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
